name: Laravel CI with Docker

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  laravel-tests:
    permissions:
      packages: read
      actions: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create env
        run: cp .env.example .env

      - name: Start services
        run: docker compose -f compose.dev.yaml up -d

      - name: run Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Run tests
        run: docker compose -f compose.dev.yaml exec workspace php artisan optimize

      - name: Run migrations
        run: docker compose -f compose.dev.yaml exec workspace php artisan migrate --force

      - name: Install NPM dependencies
        run: docker compose -f compose.dev.yaml exec workspace npm ci

      - name: Build frontend assets
        run: docker compose -f compose.dev.yaml exec workspace npm run build

      - name: Run frontend
        run: docker compose -f compose.dev.yaml exec workspace npm run dev
